/*
  ==============================================================================

    Shared precompiled header for the first / J37 tape plugin.

    Including <JuceHeader.h> pulls in every JUCE module header plus the full STL
    set used by the plugin, which is by far the most expensive part of building
    every translation unit. Compiling that once and reusing it removes tens of
    seconds from a clean build and makes incremental rebuilds far cheaper.

    Only the plugin's own translation units opt into this header. The JUCE module
    wrappers (include_juce_*.cpp) deliberately keep PrecompiledHeader = NotUsing,
    because force-injecting JuceHeader.h into them trips JUCE's own
    incorrect-use-of-JUCE-cpp-file guard.

  ==============================================================================
*/

#pragma once

#include <JuceHeader.h>

#include <algorithm>
#include <array>
#include <atomic>
#include <cmath>
#include <cstdint>
#include <memory>
#include <utility>
#include <vector>
//==============================================================================
//  Compiler compatibility shim.
//
//  The Visual Studio projects generated by the Projucer use /Fi to force-include
//  a file whose name depends on the exporter: MSVC exports pass "pch.h", while the
//  other exporters pass "stdafx.h". A toolchain that cannot find the forced file
//  (emitted as /FIstdafx.h) only warns, which would silently drop the precompiled
//  header - and every source that includes this header for the PCH would then fail
//  with C1010. Creating the file that is actually being searched for fixes that,
//  and is harmless in every other configuration.
//
//  The guards keep the two spellings from being defined twice or from overriding a
//  value that was already supplied on the command line.
//==============================================================================

#ifndef JUCE_PCH_FILE_NAME
 #define JUCE_PCH_FILE_NAME "pch.h"
#endif

#ifndef JUCE_PCH_FORCED_INCLUDE
 #define JUCE_PCH_FORCED_INCLUDE "pch.h"
#endif

#ifndef JUCE_PCH_HEADER_FILE
 #define JUCE_PCH_HEADER_FILE JUCE_PCH_FILE_NAME
#endif